<MDExCircularProgressIndicator>:
    canvas:
        Color:
            group:"active_track_color"
            rgba: self.theme_cls.primaryColor
        Line: 
            group:"active_track"
            cap:"round"
            joint:"round"
            width: self.thickness/2
        Color:
            group:"inactive_track_color"
            rgba:self.theme_cls.surfaceContainerHighestColor
        Line: 
            group:"inactive_track"
            cap:"round"
            width: self.thickness/2

<MDExLinearProgressIndicator>
    canvas:
        
        Color:
            rgba:[1,0,0,0]
        Rectangle:
            size:self.size
            pos:self.pos

        # Inactive track.
        Color:
            group:"inactive_track_color"
            rgba:[0,0,0,0]
        Line: 
            group:"inactive_track"
            cap:"round"
            joint:"round"
            width: self.thickness/2

        # Inactive track 2
        Color:
            group:"inactive_track_1_color"
            rgba:[0,0,0,0]
        Line: 
            group:"inactive_track_1"
            cap:"round"
            joint:"round"
            width: self.thickness/2


        # Active track
        Color:
            group:"active_track_color"
            rgba:[0,0,0,0]
        Line: 
            group:"active_track"
            cap:"round"
            joint:"round"
            width: self.thickness/2
            

        # Active track 2
        Color:
            group:"active_track_1_color"
            rgba:[0,0,0,0]
        Line: 
            group:"active_track_1"
            cap:"round"
            joint:"round"
            width: self.thickness/2

        # Stopper
        Color:
            group:"dot"
            rgba: self.theme_cls.primaryColor        
        
        Ellipse:
            size: [dp(4)]*2
            pos:
                (
                self.x + self.width - dp(4) - (self.thickness - dp(4))/2,
                self.center_y - dp(2)
                ) if self.orientation == "horizontal" else (
                self.center_x - dp(2),
                self.y + self.height - dp(4) - (self.thickness - dp(4))/2
                )

